### ISSUE TITLE
remove or clean up .idea folder

### ISSUE THREAD

**Issue by andregmoeller** [danihwsr/tournee#1]
I am not a 100% sure if you want to share the IntelliJ-IDE project files with other developers. If you want to share these files, please update the .gitignore file (see https://github.com/danihwsr/tournee/blob/master/.gitignore#L13-L17) and remove the .idea/workspace.xml file (see https://intellij-support.jetbrains.com/hc/en-us/articles/206544839). If you don't want to share the IntelliJ project files, please remove them.

**Comment by danihwsr** [comment]
a14b140
