### ISSUE TITLE
Optional.get() without isPresent() check

### ISSUE THREAD

**Issue by andregmoeller** [danihwsr/tournee#10]
The UserService's getByUserId and getUserByNickname methods are calling Optional.get() without an isPresent() check. Take a look at getByUserId:
```
if ( !this.userRepository.findById(id).isPresent() ) {
            String msg = String.format("User with id '%s' not found.", id);
            throw new UserNotFoundException(msg);
        }

return this.userRepository.findById(id).get();
```
The method this.userRepository.findById(id) is called twice. The first time an isPresent() check is performed, but second time no such check is performed. Yes, I admit that the probability is extremely low that the respective user gets deleted between the first and the last line. But nevertheless it could happen! I would either store the return value of this.userRepository.findById(id).get() in a variable and then reuse it or make use of the Optional's orElseThrow method.

**Comment by danihwsr** [comment]
a3810f6: Yes, that's right, thanks! Fixed with orElseThrow.
