### ISSUE TITLE
Reconsider the implementation of UserService.exists

### ISSUE THREAD

**Issue by andregmoeller** [danihwsr/tournee#2]
Please reconsider the implementation of UserService.exists. I feel that it is a bit strange that a method with the signature `private boolean exists(User user) throws UserAlreadyExistsException` either returns false or throws an exception (by the way, the last else is unnecessary). It never returns true. I feel that the name exists implies that the method returns either true or false. If you take a look at the usage, you will see that the callers expect that the method returns either true or false.

**Comment by danihwsr** [comment]
1648896
Reconsidered!
