### ISSUE TITLE
Use constructor-based injection

### ISSUE THREAD

**Issue by andregmoeller** [danihwsr/tournee#4]
Please use constructor based injection instead of field injection. This means that you don't annotate any fields with @Autorwird, but instead create a constructor taking the respective dependencies as arguments. In my opinion, constructor based injection communicates mandatory dependencies publicly and makes it easier / faster to test a class. You don't necessarily need an application context to test the respective class. You can just call the respective constructor in your test case. This is much faster than initializing the application context and then testing a specific aspect of your class. Please keep in mind that as of Spring 4.3 classes with a single constructor can omit the @Autowired annotation.

**Comment by andregmoeller** [comment]
I just saw that the UserService already makes use of constructor based injection. Please stay consistent. That said, I saw that this project is using Lombok and that the User class is annotaed with AllArgsConstructor. I would remove the hand coded constructor from UserService and annotate the class with AllArgsConstructor in order to stay consistent…

**Comment by danihwsr** [comment]
efc32b8: changed classes under src to constructor injection
