### ISSUE TITLE
Please consider using Get/Post/Put/Delete/PatchMapping

### ISSUE THREAD

**Issue by andregmoeller** [danihwsr/tournee#7]
Please consider to replace an annotation like RequestMapping(value = "/all", method = RequestMethod.GET) by a more specific annotation like GetMapping("/all"). Take a look at https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/bind/annotation/GetMapping.html.

**Comment by danihwsr** [comment]
fedfe49: reconsidered!
