### ISSUE TITLE
Strange implementation of delete

### ISSUE THREAD

**Issue by andregmoeller** [danihwsr/tournee#9]
In my opinion the implementation of the UserService's delete method looks a bit strange. I wouldn't expect that a delete method returns all the still existing entities. Instead I would expect that the method returns nothing or returns the number of removed entities or returns a list of the removed entities.

**Comment by danihwsr** [comment]
a6c4bbd: Yes, you're right! Method returns the deleted user now.

(In the beginning I just wanted a quick overview whether the repository method actually works.)
